# Generated by Django 5.0.1 on 2024-01-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlsmodel',
            name='boys',
            field=models.ManyToManyField(related_name='girls', to='relations.boysmodel'),
        ),
    ]
