# Generated by Django 5.0.1 on 2024-01-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_remove_girlsmodel_boys_girlsmodel_boys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girlsmodel',
            name='boys',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girls', to='relations.boysmodel'),
        ),
    ]
