# Generated by Django 5.0.1 on 2024-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_eventsmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedbacks')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
